import type { GridImage } from './types'

export const imagesArray: GridImage[] = [
	{
		src: "images/lier/1.jpg",
		title: "Lorem ipsum dolor sit amet.",
		description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis odio vitae arcu cursus mollis nec vel odio. Curabitur vestibulum quam vitae consectetur rhoncus.",
		project: "Project Lier",
		category: "interieur",
	},
    {
		src: "images/lier/2.jpg",
		title: "TestNiels",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/3.jpg",
		title: "Test 2",
		description: "Test niels naar Sonny",
		project: "Lier",
		category: "interieur",
	},

    {
		src: "images/mechelen/1.jpg",
		title: "",
		description: "",
		project: "Mechelen",
		category: "interieur",
	},
    {
		src: "images/mechelen/2.jpg",
		title: "",
		description: "",
		project: "Mechelen",
		category: "interieur",
	},
    {
		src: "images/mechelen/3.jpg",
		title: "",
		description: "",
		project: "Mechelen",
		category: "ruwbouw",
	},
    {
		src: "images/zemst/1.jpg",
		title: "",
		description: "",
		project: "Zemst",
		category: "interieur",
	},
    {
		src: "images/zemst/2.jpg",
		title: "",
		description: "",
		project: "Zemst",
		category: "interieur",
	},
    {
		src: "images/zemst/3.jpg",
		title: "",
		description: "",
		project: "Zemst",
		category: "interieur",
	},
    {
		src: "images/lier/4.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/5.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/6.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "ruwbouw",
	},
    {
		src: "images/lier/7.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/8.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/9.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/10.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/11.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/12.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/13.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/14.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/15.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/16.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/17.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/18.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/19.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/20.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/21.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/22.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/23.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/24.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},
    {
		src: "images/lier/25.jpg",
		title: "",
		description: "",
		project: "Lier",
		category: "interieur",
	},

    {
		src: "images/mechelen/4.jpg",
		title: "",
		description: "",
		project: "Mechelen",
		category: "interieur",
	},
    {
		src: "images/mechelen/5.jpg",
		title: "",
		description: "",
		project: "Mechelen",
		category: "interieur",
	},
    {
		src: "images/mechelen/6.jpg",
		title: "",
		description: "",
		project: "Mechelen",
		category: "interieur",
	},
    {
		src: "images/mechelen/7.jpg",
		title: "",
		description: "",
		project: "Mechelen",
		category: "interieur",
	},
    {
		src: "images/mechelen/8.jpg",
		title: "",
		description: "",
		project: "Mechelen",
		category: "interieur",
	},
    {
		src: "images/mechelen/9.jpg",
		title: "",
		description: "",
		project: "Mechelen",
		category: "interieur",
	},
    {
		src: "images/mechelen/10.jpg",
		title: "",
		description: "",
		project: "Mechelen",
		category: "ruwbouw",
	},
    {
		src: "images/mechelen/11.jpg",
		title: "",
		description: "",
		project: "Mechelen",
		category: "interieur",
	},
    {
		src: "images/mechelen/12.jpg",
		title: "",
		description: "",
		project: "Mechelen",
		category: "interieur",
	},
    {
		src: "images/mechelen/13.jpg",
		title: "",
		description: "",
		project: "Mechelen",
		category: "interieur",
	},
    {
		src: "images/mechelen/14.jpg",
		title: "",
		description: "",
		project: "Mechelen",
		category: "interieur",
	},
    {
		src: "images/mechelen/15.jpg",
		title: "",
		description: "",
		project: "Mechelen",
		category: "interieur",
	},
    {
		src: "images/zemst/4.jpg",
		title: "",
		description: "",
		project: "Zemst",
		category: "ruwbouw",
	},
    {
		src: "images/zemst/5.jpg",
		title: "",
		description: "",
		project: "Zemst",
		category: "ruwbouw",
	},
    {
		src: "images/zemst/6.jpg",
		title: "",
		description: "",
		project: "Zemst",
		category: "interieur",
	},
    {
		src: "images/zemst/7.jpg",
		title: "",
		description: "",
		project: "Zemst",
		category: "interieur",
	},
    {
		src: "images/zemst/8.jpg",
		title: "",
		description: "",
		project: "Zemst",
		category: "interieur",
	},
    {
		src: "images/zemst/9.jpg",
		title: "",
		description: "",
		project: "Zemst",
		category: "interieur",
	},
    {
		src: "images/zemst/10.jpg",
		title: "",
		description: "",
		project: "Zemst",
		category: "ruwbouw",
	},
    {
		src: "images/zemst/11.jpg",
		title: "",
		description: "",
		project: "Zemst",
		category: "interieur",
	},
    {
		src: "images/zemst/12.jpg",
		title: "",
		description: "",
		project: "Zemst",
		category: "interieur",
	},
    {
		src: "images/zemst/13.jpg",
		title: "",
		description: "",
		project: "Zemst",
		category: "interieur",
	}
];


